### ISSUE TITLE
add extension, use product.json

### ISSUE THREAD

**Issue by hadysameh** [Felx-B/vscode-web#10]
hello 
first good job 
second can you provide example how can i add a new extension that i created 
third how can i  use product.json file

**Comment by Felx-B** [comment]
Hi, thank you

I updated the stackblitz link to use a custom extension
check it out
https://stackblitz.com/edit/vscode-web

- Add your "compiled" extension in a folder
- Add a product.json file in the root folder
- Reference your extension in product.json file via `additionalBuiltinExtensions` property

**Comment by cws999** [comment]
@Felx-B 
pwd   -->  ( sample )
mkdir sample/myext/
cp -r  ${VSCODE}/extensions/akamud.vscode-theme-onedark-2.2.3/* sample/myext/
nano  product.json
`{
	"productConfiguration": {
		"nameShort": "VSCode Web Sample",
		"nameLong": "VSCode Web without FileSystemProvider",
		"applicationName": "code-web-sample",
		"dataFolderName": ".vscode-web-sample",
		"version": "1.2.3",
	}
"additionalBuiltinExtensions": [
    {
      "scheme": "theme-color",
      "path": "./myext"
    }
  ]
}`
But this still can't find the added extension
