### ISSUE TITLE
embed to angular project

### ISSUE THREAD

**Issue by bbiaudet** [Felx-B/vscode-web#11]
Hello, the project is great, but think it would be possible to import it into a component of an angular project?

**Comment by Felx-B** [comment]
Hi
I think it should be possible, but I don't think it's a good idea.
VSCode seems to be designed to be the only app on the page (window size management, key traps ...).

If you need a portion of VSCode, maybe you should use  [Monaco Editor](https://microsoft.github.io/monaco-editor/) the underlying editor of VSCode

Some package are available, for angular 
https://www.npmjs.com/search?q=ng%20monaco
