### ISSUE TITLE
Since version 1.68.0 some files are missing

### ISSUE THREAD

**Issue by t1m0thyj** [Felx-B/vscode-web#17]
First, thanks for the awesome library!

Since version 1.68.0, the `dist/node_modules` folder is missing from the package.

This causes various errors such as syntax highlighting failing to work because it can't find `vscode-onigurama`.

**Comment by Felx-B** [comment]
Hi
Thank you for reporting it, I didn't notice.
I think the behavior changed by moving from node 14 to node 16.

This should be fixed from 1.69.3

**Comment by t1m0thyj** [comment]
Thank you, can confirm this is fixed now.
