### ISSUE TITLE
Help understanding Folder URI

### ISSUE THREAD

**Issue by EmilMoe** [Felx-B/vscode-web#20]
I need some basic feedback how this `folderUri` should be understood.

I suppose the default setting is to load a sample from memory, but I would like to show content of a folder as the files. I'm building it in Docker so I will map a drive, for example on the instance files are located in `/www`. 

How should I approach displaying and editing files in that folder?

**Comment by Felx-B** [comment]
Hi
`vscode-web` is a pure browser package, so, all the `folderUri` references are client-side
You can build an extension with a `FileSystemProvider` to connect to a server API providing files or other type of document

But for your need, I think you should check out the gitpod package, which build an entire VSCode web package (browser client + server).

https://github.com/gitpod-io/openvscode-server/

This package connect the browser client VSCode directly to the VSCode server, with full capabilities (filesystem, console, extensions ...)
Beware if you expose this publicly, users will be able to do whatever they want on the server through the VSCode console

**Comment by EmilMoe** [comment]
Thanks, that makes sense I'm troubled if I am based on the wrong foundation :) 

Would gitpod be the same as using `/scripts/code-server.sh` from the core product?

**Comment by Felx-B** [comment]
I guess they are the same, but packaged.
`code-server.sh` needs you to compile and deploy your own VSCode compilation.
Gitpod seems to do it for you.
