### ISSUE TITLE
Is it possible to properly override the behavior of File > Open?

### ISSUE THREAD

**Issue by KernelDeimos** [Felx-B/vscode-web#21]
I have a web-based file open dialog I'd like to use to open files for VS Code for the We. I know it _is_ possible, but right now I'm doing it using a dynamic chain of MutationObservers that watch and modify the vscode ui on the fly as menus are created and destroyed. It's a crazy amount of logistics, so I was wondering if anyone here knows if VS Code for the Web provides a better way of doing that. If not I'll just continue using black magic to control chaos. #pleasesaveme

**Comment by Felx-B** [comment]
Hi
I think you should edit a core vscode file to acheive this, here `vscode/src/vs/workbench/services/dialogs/browser/fileDialogService.ts`, and then recompile vscode.

You can check out the `workbench.ts` file in this repo, it is meant to override the core vscode file. You can do the same for the `fileDialogService`

**Comment by KernelDeimos** [comment]
@Felx-B I tried editing `src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts`. What's odd is the app is behaving as though I changed nothing, even after I run `yarn build` and the output indicates success. I even went into `dist/out/vs/workbench/workbench.web.main.js` and I see the code I wrote in there. I'm kind of at a loss... any idea what I might be missing?

**Comment by KernelDeimos** [comment]
> You might need to clear your browser cache.

First thing I tried after I noticed the changes in workbench.web.main.js. I kept clearing it over and over again as though it would change the outcome.

**Comment by coder0107git** [comment]
Can you please see if the new file is loaded using the builtin browser dev tools?

**Comment by KernelDeimos** [comment]
I still see the original simpleFileDialog.ts from the sources inspector... that's odd. I'm not sure what to make of this, but I'll be investigating it for the next couple of hours.

**Comment by KernelDeimos** [comment]
![image](https://user-images.githubusercontent.com/7225168/211933816-d3308602-c259-47d7-a2c8-ba8e15199472.png)

Is it getting the code from a CDN instead of my build?

**Comment by KernelDeimos** [comment]
I found the really silly mistake I made and it's working great now, thanks for the help!
