### ISSUE TITLE
Source code for extension

### ISSUE THREAD

**Issue by 3BodyPeople** [Felx-B/vscode-web#22]
Can you provide the source code for the extension.js?

I want to learn how to implement the fsprovider.

Thanks.

**Comment by Felx-B** [comment]
Hi
The source code of the extension come from this repo 
https://github.com/microsoft/vscode-web-playground

I know the repo is archived, but vscode teams still use it to test the web version of vscode

**Comment by 3BodyPeople** [comment]
Thank you very much.
