### ISSUE TITLE
How to use this beyond the sample-folder

### ISSUE THREAD

**Issue by Nailington** [Felx-B/vscode-web#23]
I have built following the instructions, but am wondering how to open this without the sample-folder project. I also would like to know how to open a folder or file that exists on my harddrive? Sorry for the very basic question, and thanks!

**Comment by Felx-B** [comment]
Hi
If you need to open a file from your computer, you can use File > Open File 
and then clic on "Show Local"

![image](https://user-images.githubusercontent.com/18530681/220190596-24b6720c-3ab2-4b59-891f-1a4d7fec37d9.png)

**Comment by Nailington** [comment]
Is there a way to open an entire folder by chance?
