### ISSUE TITLE
Extension blocked with HTTPS - Mixed Content

### ISSUE THREAD

**Issue by jimetevenard** [Felx-B/vscode-web#24]
Hi Felix,

Thanks a lot for allowing us to deploy VSCode for the web without the complexity of their terrible build ! 👍 👍 

I have an Issue with your sample when served via HTTPS : 

I've done the following : 

````sh
cd sample
yarn
yarn sample # or "http-server .", or configure any static webserver you want to serve from here...
````

It works like a charm in local (`localhost`), but when **accessed via HTTPS from a server, the extension files won't load**.

The extension seem to be resolved via a non-https `Service Worker`, and blocked by the browser.  
I've tried Firefox and Chrome and booth do the same.

It's deployed here to illustrate : <https://vscode-web-issue.lab.jimetevenard.com/>

On [vscode.dev](https://vscode.dev/) all resources are resolved via https.  
Any idea on this ?

_Regards, Jim_

<img width="800" alt="Capture d’écran 2023-02-20 à 18 29 41" src="https://user-images.githubusercontent.com/23314625/220170609-74a7f3d7-d774-4b53-96d4-1fa005ba5eb8.png">

**Comment by jimetevenard** [comment]
OK, I finally found out how to fix. 👍 

I had to change the `scheme` under `additionalBuiltinExtensions` in [product.json](https://github.com/Felx-B/vscode-web/blob/06783f586bd9d05cf0e50da273a58d4250ae43b2/sample/product.json) to `https`

```diff
  // ...
  "additionalBuiltinExtensions": [
    {
-      "scheme": "http",
+      "scheme": "https",
      "path": "/myExt"
    }
]
```

This, of course, won't work locally and has to be done in my deployment pipeline.

**Comment by Felx-B** [comment]
Hi,
I'm glad you find the solution :)

If you need a dynamic scheme, to keep same codebase for localhost and deployed, you can use the dynamic version of `product.json`

By setting `window.product` variable, you'll be able to use javascript logic to define your `product` property

in your `index.html` or in any javascript file referenced:
```js
window.product = {
...
 additionalBuiltinExtensions: [
    {
      scheme: currentUrl.protocol.replace(":", ""),
      path: "/myExt
    },
  ],
...
}
```
This use of product definition is quite powerful, for example it allows dynamic routing or defining custom commands without the extension sandbox

**Comment by liweijian** [comment]
> 

Awesome, you made my day

**Comment by liweijian** [comment]
Changing the `scheme` under `additionalBuiltinExtensions` in [product.json](https://github.com/Felx-B/vscode-web/blob/06783f586bd9d05cf0e50da273a58d4250ae43b2/sample/product.json) to `https` doesn't work for me.

But this works:

```
const currentUrl = new URL(window.location.href);

window.product = {
...
 additionalBuiltinExtensions: [
    {
      scheme: currentUrl.protocol.replace(":", ""),
      path: "/myExt
    },
  ],
...
}
```

@Felx-B Awesome thanks, you made my day

**Comment by Aryan-Jagadale** [comment]
Thanks it is working @Felx-B @liweijian @jimetevenard . I was struggling lot.
