### ISSUE TITLE
LSP web extension with worker failed

### ISSUE THREAD

**Issue by liweijian** [Felx-B/vscode-web#26]
I wanna to place [this extension](https://marketplace.visualstudio.com/items?itemName=moonbit.moonbit-lang) under the `sample` folder:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/19320783/234538301-bfd5bd09-6260-430c-bf01-4d960837f27c.png">

It looks well and it has been deployed to the web server:

```
sample/moonbit$ ls
dist  language-configuration.json  LICENSE.txt  package.json  README.md  snippets  syntaxes

$ ls dist/
client.js  client.web.js  server.js  server.web.js
```

However, when I tried to run on web page, there's an error:

```
"Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://moonbit/dist/server.web.js' failed to load."
```

<img width="800" alt="image" src="https://user-images.githubusercontent.com/19320783/234539073-750cf4a6-9eb5-4bb9-9bf0-d8f275135912.png">

For the extension itself, the syntax highlight works, the snippets works. However, auto-complete not work(It depends on the `server.web.js`), just wondering if anything I'd missed?

And it's weird that the `client.web.js` loaded succeed:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/19320783/234539951-79847286-a3f7-41cb-84f0-bbc78c858030.png">

**Comment by liweijian** [comment]
The source code which load the `server.web.js`:

```ts
export function activate(context: ExtensionContext) {
  const clientOptions: LanguageClientOptions = {
    documentSelector: [{ language: 'moonbit' }],
  }
  // Create a worker. The worker main file implements the language server.
  const serverMain = Uri.joinPath(context.extensionUri, 'dist/server.web.js')

  const worker = new Worker(serverMain.toString(true))

  // create the language server client to communicate with the server running in the worker
  const client = new LanguageClient('moonbit', 'Moonbit', clientOptions, worker)

  const disposable = client.start()
  context.subscriptions.push(disposable)
}
```

**Comment by liweijian** [comment]
I did try to add the script from `index.html`:

```html
<script src="./moonbit/dist/server.web.js"></script>
```

But the extension's auto-complete still not work:
<img width="979" alt="image" src="https://user-images.githubusercontent.com/19320783/234543180-20ac7eed-193f-4e55-a2a5-1ef64aa8236e.png">

**Comment by liweijian** [comment]
I tried to install it from [Open VSX](https://open-vsx.org/extension/moonbit/moonbit-lang), and got the same error:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/19320783/234774864-904f3491-1bed-4f16-b7f2-2c9fa78c9aa8.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/19320783/234774634-0d47895d-e9a7-41e8-b6e3-1ce0c37ea921.png">

**Comment by liweijian** [comment]
<img width="862" alt="image" src="https://user-images.githubusercontent.com/19320783/234775574-fabd5f4e-091b-453e-a14c-13b931e47dfd.png">

And it works in github.dev(see the auto-complete from LSP server)

```go
type u struct {
  x:float
  y:int
}

func init {
    let h = {x:3.1, y:2}
    h.   
}
```

**Comment by lemanschik** [comment]
out of scope for this package this is not a VSCODE Implementation it is the packaging process and the dev dependencies to do your own how ever i could extract out of your screen shoots that you got type errors in your code i saw stuff like mixing of importScript:/// so you did maybe write that wrong some where and maybe 100 other failures you need to get eslint up and running first then typescript then proceed.
