### ISSUE TITLE
How to connect to a remote machine/workspace?

### ISSUE THREAD

**Issue by lapnd** [Felx-B/vscode-web#32]
Hi,
There is a usecase where user has a remote machine (or just remote container) and they want vscode-web can connect to it so that when open terminal on vscode-web, it will open terminal on that remote machine.
Can we do that with VsCode-web?

Thank!

**Comment by yportne13** [comment]
what you need is https://github.com/coder/code-server

**Comment by lapnd** [comment]
Thank you
