### ISSUE TITLE
Thanks for the awesome library!

### ISSUE THREAD

**Issue by shd101wyy** [Felx-B/vscode-web#6]
Hi there, thank you very much for building this awesome library :+1: 
I am having a few questions and it would be great if you could answer them :)

* Could you please provide us with examples of how to implement the FileSystemProvider APIs? If I would like to implement it based on your `sample` directory, then what should I do?
* Could you please provided us with examples of how to add vscode extensions (for web only of course) to your `sample`?
* How to enable the extension market in your `sample`?
* Is there a way to configure the welcome page on startup directly using `vscode-web` package?

Thank you!

**Comment by shd101wyy** [comment]
I think I have probably figured out the answers for the questions above :+1: . But here are a few new questions :)

Where can I see the possible properties for the `product.json`? Like what is `dataFolderName` in `productConfiguration` used for?
If I want to add my own extension, do I have to copy it to `node_modules/vscode-web/dist/extensions` directory? Is there another way to import extension?

Thank you!

**Comment by shd101wyy** [comment]
For example I want to change the `Commit` and `Date` in the screenshot below, then should I modify the `product.json`? If so then how should I do it? 

![Screenshot from 2021-03-29 23-46-45](https://user-images.githubusercontent.com/1908863/112863385-61f29680-90e9-11eb-8429-3a4df8e4f196.png)

**Comment by Felx-B** [comment]
Hi there, thank you for your interest in this library 😀
I'll try to summarize all the answers, but I see you already ansewered some

## FileSystemProvider sample 
Microsoft provides a bunch of extension samples here : [microsoft/vscode-extension-samples](https://github.com/microsoft/vscode-extension-samples)  
And you can find one specifically for [FileSystemProvider](https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample)

## Adding your extension
There are 2 way to do that 
 - Add your extension folder to the `node_modules/extensions` folder and add a script with the whole description, as you can see in the `demo` folder
 - Or bundle it yourself by extracting from npm package only extensions you need, and add yours. And finally build your own description file
 
 ## Marketplace
 I think you can do this by filling the `extensionsGallery` section in `product.json` but I don't think it is a good idea. Most extensions you'll find are not compatible with a web VSCode. To build a compatible extension you need to fill the `browser` property in the `package.json`. Most extension on the store do not have this.
 You can try what it would render, on the official VSCode web page https://vscode-web-test-playground.azurewebsites.net/
 
 ## Welcome page
 I don't think you can do this until the VSCode team allow extension API on the welcome page.
 But you can create an extension, which runs on startup and open a custom page via `vscode.open` command
 
 ## Product.json reference 
 You found it some of the information but there's more.
 product.json has `IWorkbenchConstructionOptions & { folderUri?: UriComponents, workspaceUri?: UriComponents }` type
 So you can specify both workbench options and folder or workspace to open.
 [IWorkbenchConstructionOptions](https://github.com/microsoft/vscode/blob/3287cedd3430bd4749f32fa5975402499279a745/src/vs/workbench/workbench.web.api.ts#L239) which contains the `productConfiguration` you found.
 ```json
{
	"productConfiguration": {
		"nameShort": "Code Web",
		"nameLong": "Code Web",
		"applicationName": "code-web",
		"dataFolderName": ".vscode-web",
		"version": "1.2.3"
	},
	"defaultLayout": {
        ...
        },
	"configurationDefaults": {
         // Custom settings
        },
	"folderUri": {
		"scheme": "memfs",
		"path": "/sample-folder"
	}
	...
}
 ```
 If you want to go further, you can also provide the product.json content through `window.product`, this way you can handle a full static website and manage to build a tool like [github1s](https://github1s.com/microsoft/vscode) (I managed to built it with this library, but it didn't fit the needs of the team https://github.com/conwnet/github1s/pull/118)

**Comment by shd101wyy** [comment]
Thanks a lot @Felx-B 👍 
Your answer helps a lot

**Comment by shd101wyy** [comment]
I am currently building markdown note taking application called [Crossnote](https://github.com/0xGG/crossnote). But I am not very satisfied with its current editor. So I am considering replacing it with vscode and add the note taking functionality as vscode extension. Your library seems to be a good choice to use :+1: I will see how far I could go. Thank you!

**Comment by shd101wyy** [comment]
Hi @Felx-B . This question is not related to **vscode-web**, but I am just curious if you know any solution.  
I am now trying to build a vscode extension for the web side that calls the `window.showDirectoryPicker` to open a local directory right inside the browser. Below are the source files

https://github.com/0xGG/vscode-native-file-system/tree/master/src

However, it seems like vscode extension is running as javascript worker, so my extension code has problem calling the `window` object. Do you know any workaround of it? Thank you!

**Comment by Felx-B** [comment]
Hi
I remember trying to do this, but unfortunately didn't manage to do it.
I think VS Code team must write custom stuff to allow it.

One way I didn't try is a full custom webview, where the user click on a button to trigger the picker. The webview should stores the handler in [IndexedDB](https://web.dev/file-system-access/#storing-file-handles-or-directory-handles-in-indexeddb) 
And then, the FileSystemProvider should recover it from indexedDB and use it to provide the native filesystem.

I think it should work, but the user experience will be pretty ugly.

**Comment by Felx-B** [comment]
Hey @shd101wyy ! I think I found a better way 😀

You need to create a native vscode command. Instead of using a `product.json` file, simply fill the `window.product` property  in your index.html (or in a custom javascript file):
```javascript
 window.product = {
      productConfiguration: {
        nameShort: "VSCode Web Sample",
        version: "1.2.3.4",
        ...
      },
      folderUri: {
        scheme: "cfs",
        path: "/",
      },
      commands: [
        {
          id: "custom.storeDirectoryHandle",
          handler: async () => {
            // get handle from indexedDB or ask user
            ...
            const dirHandle = await window.showDirectoryPicker();
            // TODO store handle in indexedDB, in pure JS
          }
        }
      ]
    };
```

After you did this, you can create a proper command in your extension, which can be bound to a button somewhere, or a user command call. (It should not be automatic on load, Chrome won't allow it).

After that you should be able to retrieve your handle from IndexedDB, from your FileSystemProvider

**Comment by shd101wyy** [comment]
@Felx-B This is fantastic! I will try it tomorrow!! Thanks a lot!!!

**Comment by shd101wyy** [comment]
I just tried it quickly by adding `window.product` variable, but it doesn't seem to be working. Then I checked the built `workbench.js` and it looked like below after beautify:

```javascript
(function () {
  var e = ["vs/code/browser/workbench/workbench", "require", "exports", "vs/workbench/workbench.web.api", "vs/base/common/uri"];
  define(e[0], function (r) {
    for (var o = [], n = 0, i = r.length; n < i; n++) o[n] = e[r[n]];
    return o
  }([1, 2, 3, 4]), (function (e, r, o, n) {
    "use strict";
    Object.defineProperty(r, "__esModule", {
      value: !0
    }), async function () {
      const e = await fetch("product.json");
      let r, i = await e.json();
      if (Array.isArray(i.staticExtensions) && i.staticExtensions.forEach(e => {
          e.extensionLocation = n.URI.revive(e.extensionLocation)
        }), r = i.folderUri ? {
          folderUri: n.URI.revive(i.folderUri)
        } : i.workspaceUri ? {
          workspaceUri: n.URI.revive(i.workspaceUri)
        } : void 0) {
        const e = {
          workspace: r,
          open: async () => {}
        };
        i = Object.assign(Object.assign({}, i), {
          workspaceProvider: e
        })
      }
      o.create(document.body, i)
    }()
  }))
}).call(this);
```

It seems like `window.product` is not there so not my `window.product` in `index.html` is not used. 
Do you have any clue? Thank you!

**Comment by shd101wyy** [comment]
Hmmm weird. https://cdn.jsdelivr.net/npm/vscode-web@1.55.0/dist/vscode/vs/code/browser/workbench/workbench.js seems to be right. I will try a clean install later.

**Comment by shd101wyy** [comment]
Hi @Felx-B . I am sorry to bother you again. I see https://github.com/Felx-B/vscode-web/blob/main/workbench.ts#L25 uses `workspace = { folderUri: URI.revive(config.folderUri) }`. However, I see https://github.com/microsoft/vscode/blob/3287cedd3430bd4749f32fa5975402499279a745/src/vs/workbench/services/host/browser/browserHostService.ts#L43 defined `readonly workspace: IWorkspace;` doesn't have `folderUri` nor `workspaceUri`. Is this a bug? Thanks!

**Comment by shd101wyy** [comment]
btw, I tried the [FileSystemProvider](https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample) example using vscode-web. However, when I ran it in browser with an empty workspace and executed `MemFS: Setup Workspace` command, I got the error `Uncaught Error: Empty workspace is not supported in browser when there is no remote connection.` and no folder was created. Do you have any suggestions how to get [FileSystemProvider](https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample) working in browser? Thank you!

**Comment by shd101wyy** [comment]
https://0xgg.io/vscode-web-with-native-filesystem/

I got it working!!! Thanks!!!! :smile:

**Comment by mecirmartin** [comment]
> btw, I tried the [FileSystemProvider](https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample) example using vscode-web. However, when I ran it in browser with an empty workspace and executed `MemFS: Setup Workspace` command, I got the error `Uncaught Error: Empty workspace is not supported in browser when there is no remote connection.` and no folder was created. Do you have any suggestions how to get [FileSystemProvider](https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample) working in browser? Thank you!
> 
> Update: nvm I got this working :)

Could you please explaain how you got this working? I created my own FS with all the implementations, now i'm facing the problem with empty workspace.

Thanks for help

**Comment by Felx-B** [comment]
Hi
You need to fill the `folderUri` or ˋworkspaceUri` in your ˋpackage.json` file.
You should set the scheme of your custom FSProvider

"folderUri": {
   	"scheme": "memfs",
   	"path": "/sample-folder"
   }

**Comment by Aryan-Jagadale** [comment]
I am still facing issue in filesystem provider, can you tell me how to do that ?
