### ISSUE TITLE
Register FileSystemHandle metadata for common text/code files

### ISSUE THREAD

**Issue by rayfoss** [Felx-B/vscode-web#7]
- https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-files
- https://caniuse.com/mdn-api_filesystemhandle
- https://web.dev/file-handling/
- https://excalidraw.com/

Example of what it looks like with the Excalidraw PWA (This is in no way a native App, this was installed by chrome from the URL):
![Screenshot 2022-02-03 16 37 04](https://user-images.githubusercontent.com/876076/152441127-f81e2f1e-9274-4bf6-9022-b4482971b1dc.png)

**Comment by Felx-B** [comment]
I don't really understand the question here.
But I think what your are looking for is to use vscode-web as a local file editor.

Now VSCode have those features built-in

### Open a local file
- Run the vscode-web sample
- Press CMD + O
- you can also find this in the Menu
  -  File -> Open File

### Open a local folder
- Run the vscode-web sample
- Click on "Add a folder" in the file explorer 
![image](https://user-images.githubusercontent.com/18530681/152232767-48c4e953-b5ad-4555-b91f-43121bf2bd54.png)

**Comment by rayfoss** [comment]
Currently when I want to edit a JSON, csv, md or js file I just downloaded, If I right click on it in the file manager, vscode-web doesn't show up as an option, despite being installed. There is now an API to make it show up... XCalidraw uses it and I've attached a screenshot of their use in the OP

Here's what it currently looks like when I right click a json file in my file manager, notice the absence of vscode-web:
 
![Screenshot 2022-02-03 16 35 25](https://user-images.githubusercontent.com/876076/152441485-5c0634a9-822d-4cb2-800f-676205a06909.png)

**Comment by hello-smile6** [comment]
> Currently when I want to edit a JSON, csv, md or js file I just downloaded, If I right click on it in the file manager, vscode-web doesn't show up as an option, despite being installed. There is now an API to make it show up... XCalidraw uses it and I've attached a screenshot of their use in the OP
> 
> Here's what it currently looks like when I right click a json file in my file manager, notice the absence of vscode-web:
> 
> ![Screenshot 2022-02-03 16 35 25](https://user-images.githubusercontent.com/876076/152441485-5c0634a9-822d-4cb2-800f-676205a06909.png)
> 
> This also allows setting vscode-web as the default file handler, which can make opening a csv or txt report go from a 5 click process, down to a single click process.

@rayfoss 
Think this would be an issue better suited for <a href="https://github.com/microsoft/vscode"><code>microsoft/vscode</code></a>

**Comment by rayfoss** [comment]
VSCode is distributed as a native app, they have no need to implement new web APIs... specially as this is most useful for non-DOS based operating systems like M1 Macs and web based OSs popular in schools.

Would you consider a PR that registers vscode-web as a csv, txt and html app with FileSystemHandle?

**Comment by hello-smile6** [comment]
> VSCode is distributed as a native app, they have no need to implement new web APIs... specially as this is most useful for non-DOS based operating systems like M1 Macs and web based OSs popular in schools.
> 
> Would you consider a PR that registers vscode-web as a csv, txt and html app with FileSystemHandle?

They have a web app! Also, they have an app for M1 macs! DO YOUR RESEARCH!

**Comment by rayfoss** [comment]
I'm going to have to find that web-app... this is the repo I landed on while searching for that web app. Their M1 mac app is based on electron... meaning it's not as battery optimized for the M1 as a Safari backed PWA.
